export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';
export const FETCHING_DATA_REQUEST = 'FETCHING_DATA_REQUEST';
export const BASE_URL = 'http://localhost:8080/api/bananas';
